name: Release Docker image

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Release Version and Sanitize Name
        id: prep
        run: |
          # Get the version from the tag
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          # Convert username/repo to lowercase to avoid Docker tagging issues
          RAW_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/calculator"
          echo "IMAGE_NAME=${RAW_IMAGE,,}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.prep.outputs.VERSION }} .

      - name: Save Docker image
        run: |
          docker save ${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.prep.outputs.VERSION }} | gzip > calculator-${{ steps.prep.outputs.VERSION }}.tar.gz

      - name: Upload image to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: calculator-${{ steps.prep.outputs.VERSION }}.tar.gz

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push image
        run: |
          docker push ${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.prep.outputs.VERSION }}
